"""empty message

Revision ID: 8bab3165c343
Revises: 
Create Date: 2024-10-02 09:48:49.218694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bab3165c343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('u_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('dailyinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('food_name', sa.String(length=64), nullable=True),
    sa.Column('food_calories', sa.Float(), nullable=True),
    sa.Column('exercise_name', sa.String(length=64), nullable=True),
    sa.Column('exercise_duration', sa.Float(), nullable=True),
    sa.Column('weight_target', sa.Float(), nullable=True),
    sa.Column('bmr_target', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['users.u_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailyinfo')
    op.drop_table('users')
    # ### end Alembic commands ###
